-- Create a lightweight per-user chat history table
create table if not exists public.chat_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question text not null,
  answer text not null,
  created_at timestamptz not null default now()
);

alter table public.chat_history enable row level security;

-- RLS policies: users can insert/select their own rows
create policy "read own chat history"
on public.chat_history for select
using (auth.uid() = user_id);

create policy "insert own chat history"
on public.chat_history for insert
with check (auth.uid() = user_id);


